### ISSUE TITLE
Purpose of architecture

### ISSUE THREAD

**Issue by MusayevKamran** [alexeyzimarev/ddd-book#1]
Can I Use this architecture on Online Money Transfer or Online Banking. The size of project will not be very large or project will readable and easy updatable? Is it suitable for this purpose or you recommends another type of architecture ?

**Comment by alexeyzimarev** [comment]
Sorry for two years delay. This repository is a collection of samples for the book. It doesn't represent any particular architecture, although it demonstrates some patterns. I am unable to give you any advice on using principles, patterns, or ways of implementing things I wrote in the book and demonstrated with examples in this repository, to build any kind of production system, as I am not involved with your organisation and business.
