### ISSUE TITLE
Chapter 12 in table of contents leads to 404

### ISSUE THREAD

**Issue by michal880** [alexeyzimarev/ddd-book#2]
* Steps to reproduce:
go to  README.md, navigate to table of contents, click chapter 12

* Unexpcted behaviour:
link leads to 404 on https://github.com/alexeyzimarev/ddd-book/tree/master/chapter12

**Comment by alexeyzimarev** [comment]
Closed in https://github.com/alexeyzimarev/ddd-book/commit/f2edec94dca292aa05fd27784a933fdc82490ca8
